import {
  GridViewIcon,
  Building06Icon,
  UserMultipleIcon,
  Layers01Icon,
  Location01Icon,
  UserGroupIcon,
  Settings02Icon,
  Package01Icon,
  ServiceIcon,
  Target01Icon,
  FileValidationIcon,
  StarIcon,
  Wallet01Icon,
  CreditCardIcon,
  Megaphone01Icon,
  Layout02Icon,
} from "hugeicons-react";
import type { NavItem } from "../types/nav";

export const navItems: NavItem[] = [
  { label: "Dashboard", path: "/", icon: GridViewIcon },
  { label: "Businesses", path: "/businesses", icon: Building06Icon },
  { label: "Users", path: "/users", icon: UserMultipleIcon },
  { label: "Categories", path: "/categories", icon: Layers01Icon },
  { label: "Products", path: "/products", icon: Package01Icon },
  { label: "Services", path: "/services", icon: ServiceIcon },
  { label: "Leads", path: "/leads", icon: Target01Icon },
  { label: "RFQs", path: "/rfqs", icon: FileValidationIcon },
  { label: "Reviews", path: "/reviews", icon: StarIcon },
  { label: "Subscriptions", path: "/subscriptions", icon: Wallet01Icon },
  { label: "Payments", path: "/payments", icon: CreditCardIcon },
  { label: "Advertisements", path: "/advertisements", icon: Megaphone01Icon },
  { label: "CMS", path: "/cms", icon: Layout02Icon },
  { label: "Locations", path: "/locations", icon: Location01Icon },
  { label: "Admin Users", path: "/admin-users", icon: UserGroupIcon },
  { label: "Settings", path: "/settings", icon: Settings02Icon },
];
